language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

# Since there's only one file in here and no dependencies,
# we can get by without composer
# and run in PHP 5.2
script: make run-unit-tests
